### ISSUE TITLE
Is there a list of what this mod actually does, or how to use it?

### ISSUE THREAD

**Issue by Tenome** [JoshuaMKW/BetterSunshineEngine#15]
I stumbled across this, but I'm not sure if it's a mod that improves Sunshine, or if it's more of a framework for other mods. I extracted an ISO and applied the files, but I don't notice any changes so far (aside from the title of the game changing to Super Mario Eclipse). I also can't find a config file/menu.

**Comment by JoshuaMKW** [comment]
Ah, the game getting renamed to Super Mario Eclipse was unintended, and I know exactly why that happened, too. Thank you for letting me know so I can revert that change.

As for the other stuff, Better Sunshine Engine is designed to be a mod framework, but it also comes prepackaged with some general QOL patches you can apply in the game. You can go to the in-game settings menu to see if it is now custom. You can follow the on-screen button prompts and change stuff to your liking.

I'll leave this issue open for a day or until you confirm that this has helped address your concerns.

**Comment by Tenome** [comment]
Thanks. I've since installed Sunburn and realized it's a framework, and found the options menu. I didn't look into it hard enough, my bad.
