### ISSUE TITLE
Jumping on yoshi produces an error on Dolphin

### ISSUE THREAD

**Issue by digivee** [JoshuaMKW/BetterSunshineEngine#22]
![image](https://github.com/DotKuribo/BetterSunshineEngine/assets/14162763/6ccdfa6f-dabf-4962-ae8b-55f143c9b0d4)

Upon jumping on Yoshi, I get this error every time. It can be ignored, but it happens every time. Most recent Dolphin version, disabled all other visual mods, etc, to try and fix it.

**Comment by JoshuaMKW** [comment]
This is fixed in the development branch of Better Sunshine Engine, and will apply in the next release. I will keep this issue open in the meantime though for other people to see.
