### ISSUE TITLE
Entering Hotel Delfino's Casino causes an Exception/Crash on Dolphin

### ISSUE THREAD

**Issue by digivee** [JoshuaMKW/BetterSunshineEngine#23]
![image](https://github.com/DotKuribo/BetterSunshineEngine/assets/14162763/0dd97fad-2351-4abb-a414-70deca6802d7)
![image](https://github.com/DotKuribo/BetterSunshineEngine/assets/14162763/692f9e3a-b1d7-46fd-b4d7-54744b8675b5)

Replicable by just entering the Casino after talking to the Pianta guarding the door. Disabled all graphics mods, updated Dolphin, etc

**Comment by JoshuaMKW** [comment]
This appears to already be fixed in the development build of Better Sunshine Engine, so I will leave this open until the next release.
