### ISSUE TITLE
Parallel projection

### ISSUE THREAD

**Issue by micheleod** [JoshuaMKW/BetterSunshineEngine#25]
I was wondering if it's possible to add a feature that allows to play Super Mario Sunshine with a parallel/orthographic projection (i.e. axonometry) instead of the standard perspectival projection.

**Comment by JoshuaMKW** [comment]
It is possible, but explain the practical purpose you are looking for in this? I'll try to add it if I think it is worth the time.

**Comment by micheleod** [comment]
Thank you very much for your fast response. For me, it's because I would enjoy playing the game in parallel projection. I do think, however, that it would be useful for others in different ways: for example, having a parallel camera allows for a more "neutral" representation of the game scene, and this can be used to provide useful diagrams (e.g. it's used in this video to explain some mario 64 glitches: https://www.youtube.com/watch?v=YsXCVsDFiXA)

**Comment by JoshuaMKW** [comment]
I decided to poke around and see if I could quickly throw in orthographic support, however it seems to break a lot of visuals and overall not produce a result worthy of use. Thus I'm going to close this feature request for the time being. After all, it's no good if the skybox disappears and the NPC's faces vanish :P
