### ISSUE TITLE
Blooper Surfing Safari and The Secret of Ricco Tower Have Swapped Fluddless Flags

### ISSUE THREAD

**Issue by XModxGodX** [JoshuaMKW/BetterSunshineEngine#26]
When entering mission 2's sub area of Ricco Harbor the shadow mario stealing fludd cutscene plays and you end up without fludd for that part and the 4th mission doesn't have it when it should even has the red coin switch available from the start doesn't really effect a run that much but it's still not intended.

**Comment by JoshuaMKW** [comment]
I've been made aware of this pretty recently. I'm planning to have a hotfix released within the next few days to address the issue.
